### ISSUE TITLE
Criar o ambiente de desenvolvimento

### ISSUE THREAD

**Issue by rodrigos4y** [services4youbr/website-institucional#5]
Criar o ambiente para o desenvolvimento

**Comment by victorinno** [comment]
Favor especificar melhor :P

**Comment by rodrigos4y** [comment]
Na parte de Frontend, para colaborar nesse projeto precisa ter instalado no seu computador:

- Node.js
Para instalar o Nodejs, acesse ao [site do Nodejs](https://nodejs.org/en/download/), escolha o link de acordo com seu sistema operacional  e faça o download. Com o Nodejs também é instalado o npm
- Angular
Para instalaro angular é necessário ter instalado o Nodejs. Abra o terminal e digite: `npm install -g @angular/angular-cli`
- Sass
Para utilizar o Sass, acesse o [site do Sass](https://sass-lang.com/) e veja como é feita a instalação
- Bootstrap 4
Para utilizar o Bootstrap, acesse o [site do Bootstrap](https://getbootstrap.com), escolha a versão 4.1.

**Comment by rodrigos4y** [comment]
- Protractor
Suite de testes do Angular. Para instalar o Protractor, abra o terminal, vá até a sua pasta desse projeto e digite: `npm install -g protractor --save-dev`. Após ter instalado o Protractor, você precisará atualizar o webdriver-manager. no terminal digite o comando: `npm install webdriver-manager --save-dev`

**Comment by rodrigos4y** [comment]
Já estamos com tudo pronto para o acompanhamento do projeto e tudo que precisamos para o desenvolvimento
